### ISSUE TITLE
Seeking new maintainer(s)

### ISSUE THREAD

**Issue by morgant** [kzkn/gretel#19]
> Unfortunately @lassebunk passed away shortly after I had talked with him about helping to maintain the gem. When @MrShemek and I created the fork we were hoping to be able to keep this gem going, at least for maintenance.
> 
> I haven't heard from @MrShemek in awhile now, and unfortunately I have not been doing much ruby work as of late, and so I haven't had the time to put in the maintenance that is required.
> 
> If anyone would like to take over responsibility for getting a new release out with this fix and with others, that would be appreciated. I'm happy to help insofar as transferring ownership and facilitating a transition, but I don't have much time to dedicate to maintenance right now.

_Originally posted by @WilHall in https://github.com/WilHall/gretel/issues/16#issuecomment-589726235_

**Comment by kzkn** [comment]
I will continue to maintain this project. Thanks for open issue.

**Comment by morgant** [comment]
@kzkn Many thanks!
