### ISSUE TITLE
JSON-LD support

### ISSUE THREAD

**Issue by dkniffin** [kzkn/gretel#25]
I've started using this gem for breadcrumbs on my site, and it's been great so far. I initially used the built-in generator for the breadcrumb HTML, but it didn't quite fit my requirements so I opted for creating them by hand using the `breadcrumbs` method. However in doing so, I lost the semantic breadcrumb functionality. I'm working on a replacement using the JSON-LD/`ld+json` version (as seen [here](https://developers.google.com/search/docs/data-types/breadcrumb#json-ld)). It would be awesome if this library supported that natively.

I'll likely have a PR to add this functionality before long. I hope you'll be willing to merge it. Stay tuned.

**Comment by kzkn** [comment]
@dkniffin 
I see. The semantic breadcrumbs feature that gretel has is not helpful when making them manually.

It is a great suggestion. I look forward to merge it.
