### ISSUE TITLE
Publish a new version with current master HEAD to suport Rails 7.0

### ISSUE THREAD

**Issue by matsubo** [kzkn/gretel#34]
# Abstract

The head of master branch seems supports Rails 7.0.
https://github.com/kzkn/gretel/blob/master/gretel.gemspec#L22

However the newest release, 4.3.0 supports only less than 7.0.

## Workaround1
If I downgrade gretel to `4.0.2` which does not have rails dependency, I can use but the release is too old to use. I want to use `structured_data` which is implemented after the 4.0.2 release.

## Workaround 2

Specify the branch name directly in the Gemfile.
```
gem 'gretel', git: 'https://github.com/kzkn/gretel', branch: 'master'
```

**Comment by kzkn** [comment]
Thanks for your comment. I've released 4.4.0!
