### ISSUE TITLE
Add data attribute to link

### ISSUE THREAD

**Issue by rctneil** [kzkn/gretel#37]
Hi,

On one of my links, I need to add a data attribute like below:

data-turbo-frame="_top"

How can I add this?

**Comment by kzkn** [comment]
There are no way to add some custom attributes for link elements with building the breadcrumbs automatically. Perhaps [buliding the breadcrumbs manually](https://github.com/kzkn/gretel#building-the-breadcrumbs-manually) would work.

I think the ability to add custom attributes for link elements is useful. PR is welcome :smile:
