### ISSUE TITLE
Detach a fork

### ISSUE THREAD

**Issue by alec-c4** [kzkn/gretel#46]
Hey!
I think it would be useful if you detach a fork, but keep link to original repo in README. When you create a PR - you'll be routed to an active repo, but not an abandoned one.

There are how-to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork

**Comment by kzkn** [comment]
@alec-c4 
I will try. Thanks for letting me know :smiley:
